### ISSUE TITLE
beforeScenario documentation

### ISSUE THREAD

**Issue by asgerjensen** [artilleryio/artillery#1469]
The website (https://www.artillery.io/docs/guides/guides/http-reference) says this about `beforeScenario` :

```
Setting scenario-level hooks
Similarly, a scenario definition can have beforeScenario and afterScenario attributes, which will make the specified functions run for every request in the scenario.

scenarios:
  - beforeScenario: "setApiKey" # Run the function before each request.
    afterScenario: "logResults" # Run the function after each request.
    flow:
      - get:
          url: "/search?q={{ query }}"
      - get:
          url: "/products"
```

Which does not match with the observed behavior, which is that beforeScenario will run ONCE pr vuser, before making ANY requests, so in the flow above, neither `get` would see any `apiKey`

That being said, the documented example does fit with the documented behavior to make it so you dont have to have `beforeRequest: setApiKey` and `afterResponse: logIfFailing` for every single request in the flow. It just, does not fit with the actual behavior

**Comment by hassy** [comment]
That's an error in the docs, thank you for letting us know @asgerjensen! fixed now.

As the name suggests, `beforeScenario` / `afterScenario` are meant to run once per scenario execution (= VU)

**Comment by asgerjensen** [comment]
Hi,
Thank you for your quick reply. 

The example is still not clear to me. If we assume the beforeScenario makes some call to establish the apiToken, what mechanism would set it on each of the requests in that VUs flow?

I find that i have to add the header with a beforeRequest on every call, which is tedious,
but maybe i am missing something. Is it possible to set something like defaultHeaders or something in a beforeScenario?
