### ISSUE TITLE
Error: Callback was already called.

### ISSUE THREAD

**Issue by meetveera** [artilleryio/artillery#1525]
Version info: 
```
npm install artillery
```

Running this command: 
```
artillery run soa.yaml 
```

I expected to see this happen:

The APIs getting executed

Instead, this happened:

But getting the following error:

```
worker error, id: 1 Error: Callback was already called.
    at /usr/local/lib/node_modules/artillery/node_modules/async/dist/async.js:969:32
    at /usr/local/lib/node_modules/artillery/core/lib/engine_http.js:700:20
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by MMaximus111** [comment]
Yesterday on the last docker image `artilleryio/artillery` I  have the same error
![Untitled](https://user-images.githubusercontent.com/98421643/180390947-b946447d-df9a-4359-b191-dae0f5c020cc.png)

**Comment by hassy** [comment]
thank you @meetveera & @MMaximus111, looking into it

**Comment by hassy** [comment]
should be fixed in https://github.com/artilleryio/artillery/commit/080d0916a0e0bfd59928f8efe7f792c3bf8596f4 - new release to follow asap

**Comment by meetveera** [comment]
Thank you @hassy . Let us know once the new release is out to install

**Comment by hassy** [comment]
This should be fixed in `v2.0.0-22` now

**Comment by meetveera** [comment]
Hi @hassy :

I reinstalled the latest version of artillery using the below command:
```npm install -g artillery@v2.0.0-22```

Ran the below command to execute artillery script and I am still getting the same error and the run is going in a infinite loop.

```artillery run my-file.yaml -e dev --quiet```

Below is the error I am still getting:

```
worker error, id: 1 Error: Callback was already called.
    at /usr/local/lib/node_modules/artillery/node_modules/async/dist/async.js:969:32
    at /usr/local/lib/node_modules/artillery/core/lib/engine_http.js:698:20
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by vlxdisluv** [comment]
Hi @hassy

I have installed the last version:
`Artillery: 2.0.0-31`

Run the test ws connections i get error:
` worker error, id: 5 Error: Callback was already called.
    at /Users/vlxdisluv/.nvm/versions/node/v16.15.0/lib/node_modules/artillery/node_modules/async/dist/async.js:969:32
    at done (/Users/vlxdisluv/.nvm/versions/node/v16.15.0/lib/node_modules/artillery/node_modules/@artilleryio/int-core/lib/engine_socketio.js:344:16)
    at Socket.<anonymous> (/Users/vlxdisluv/.nvm/versions/node/v16.15.0/lib/node_modules/artillery/node_modules/@artilleryio/int-core/lib/engine_socketio.js:316:7)
    at Socket.on (/Users/vlxdisluv/.nvm/versions/node/v16.15.0/lib/node_modules/artillery/node_modules/@socket.io/component-emitter/index.js:63:8)
    at Socket.Emitter.emit (/Users/vlxdisluv/.nvm/versions/node/v16.15.0/lib/node_modules/artillery/node_modules/@socket.io/component-emitter/index.js:143:20)
    at Socket.onerror (/Users/vlxdisluv/.nvm/versions/node/v16.15.0/lib/node_modules/artillery/node_modules/socket.io-client/build/cjs/socket.js:437:18)
    at Manager.Emitter.emit (/Users/vlxdisluv/.nvm/versions/node/v16.15.0/lib/node_modules/artillery/node_modules/@socket.io/component-emitter/index.js:143:20)
    at Socket.<anonymous> (/Users/vlxdisluv/.nvm/versions/node/v16.15.0/lib/node_modules/artillery/node_modules/socket.io-client/build/cjs/manager.js:152:18)
    at Socket.Emitter.emit (/Users/vlxdisluv/.nvm/versions/node/v16.15.0/lib/node_modules/artillery/node_modules/@socket.io/component-emitter/index.js:143:20)
    at Socket.onError (/Users/vlxdisluv/.nvm/versions/node/v16.15.0/lib/node_modules/artillery/node_modules/engine.io-client/build/cjs/socket.js:554:14)`
